"""removing constraint

Revision ID: 04141db424c6
Revises: 
Create Date: 2020-06-24 21:25:39.349850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04141db424c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('fax', sa.String(length=64), nullable=True),
    sa.Column('sub_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('measurement', sa.String(length=255), nullable=True),
    sa.Column('dosage_form', sa.String(length=255), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('drug_class', sa.String(length=255), nullable=True),
    sa.Column('public', sa.String(length=2), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('fax', sa.String(length=64), nullable=True),
    sa.Column('alt_phone', sa.String(length=64), nullable=True),
    sa.Column('alt_fax', sa.String(length=64), nullable=True),
    sa.Column('bin', sa.String(length=64), nullable=True),
    sa.Column('pcn', sa.String(length=64), nullable=True),
    sa.Column('group', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('fax', sa.String(length=255), nullable=True),
    sa.Column('income_threshold', sa.Integer(), nullable=True),
    sa.Column('household_size', sa.Integer(), nullable=True),
    sa.Column('required_docs', sa.String(length=255), nullable=True),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('public', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['drug_name'], ['drugs.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('prescriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('lname', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=640), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.Integer(), nullable=True),
    sa.Column('npi', sa.Integer(), nullable=True),
    sa.Column('dea', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('fax', sa.String(length=64), nullable=True),
    sa.Column('alt_phone', sa.String(length=64), nullable=True),
    sa.Column('alt_fax', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dea'),
    sa.UniqueConstraint('npi')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('lname', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('lname', sa.String(length=64), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('ins_eff_date', sa.DateTime(), nullable=True),
    sa.Column('ins_term_date', sa.DateTime(), nullable=True),
    sa.Column('allergies', sa.String(length=640), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.String(length=640), nullable=True),
    sa.Column('disease_states', sa.String(length=640), nullable=True),
    sa.Column('address', sa.String(length=640), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('ins_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('date_last_mod', sa.DateTime(), nullable=True),
    sa.Column('date_closed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['ins_id'], ['insurance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mapapplication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('map_name', sa.String(length=255), nullable=True),
    sa.Column('init_notes', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('fax', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('ins_id', sa.Integer(), nullable=False),
    sa.Column('ins_name', sa.String(length=64), nullable=True),
    sa.Column('pt_id', sa.Integer(), nullable=False),
    sa.Column('pt_info', sa.String(length=255), nullable=True),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=64), nullable=False),
    sa.Column('md_id', sa.Integer(), nullable=True),
    sa.Column('date_open', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['drug_name'], ['drugs.name'], ),
    sa.ForeignKeyConstraint(['ins_id'], ['insurance.id'], ),
    sa.ForeignKeyConstraint(['ins_name'], ['insurance.name'], ),
    sa.ForeignKeyConstraint(['map_id'], ['map.id'], ),
    sa.ForeignKeyConstraint(['md_id'], ['prescriber.id'], ),
    sa.ForeignKeyConstraint(['pt_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('priorauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ins_id', sa.Integer(), nullable=False),
    sa.Column('ins_name', sa.String(length=64), nullable=True),
    sa.Column('prescriber_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('date_open', sa.DateTime(), nullable=False),
    sa.Column('date_last_mod', sa.DateTime(), nullable=True),
    sa.Column('eff_date', sa.DateTime(), nullable=True),
    sa.Column('term_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('drug', sa.String(length=64), nullable=True),
    sa.Column('notes_init', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['ins_id'], ['insurance.id'], ),
    sa.ForeignKeyConstraint(['ins_name'], ['insurance.name'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['prescriber_id'], ['prescriber.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('doc_path', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('ins_id', sa.Integer(), nullable=True),
    sa.Column('pt_id', sa.Integer(), nullable=True),
    sa.Column('pa_id', sa.Integer(), nullable=True),
    sa.Column('md_id', sa.Integer(), nullable=True),
    sa.Column('public', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['ins_id'], ['insurance.id'], ),
    sa.ForeignKeyConstraint(['md_id'], ['prescriber.id'], ),
    sa.ForeignKeyConstraint(['pa_id'], ['priorauth.id'], ),
    sa.ForeignKeyConstraint(['pt_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=64), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('ins_id', sa.Integer(), nullable=True),
    sa.Column('pt_id', sa.Integer(), nullable=True),
    sa.Column('pa_id', sa.Integer(), nullable=True),
    sa.Column('md_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['ins_id'], ['insurance.id'], ),
    sa.ForeignKeyConstraint(['md_id'], ['prescriber.id'], ),
    sa.ForeignKeyConstraint(['pa_id'], ['priorauth.id'], ),
    sa.ForeignKeyConstraint(['pt_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    op.drop_table('documents')
    op.drop_table('priorauth')
    op.drop_table('mapapplication')
    op.drop_table('patient')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('prescriber')
    op.drop_table('map')
    op.drop_table('insurance')
    op.drop_table('drugs')
    op.drop_table('clients')
    # ### end Alembic commands ###
