"""adding map and map app notes

Revision ID: 8d82df5f7dfd
Revises: 04141db424c6
Create Date: 2020-07-01 14:15:59.965591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d82df5f7dfd'
down_revision = '04141db424c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('map_id', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('mapapp_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'mapapplication', ['mapapp_id'], ['id'])
    op.create_foreign_key(None, 'notes', 'map', ['map_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'mapapp_id')
    op.drop_column('notes', 'map_id')
    # ### end Alembic commands ###
